import Head from 'next/head';
import Link from 'next/link';
import { Navbar } from '../Navbar';
import styles from './MainLayout.module.css';
import { FC, FunctionComponent, ReactElement } from 'react';

interface Layout {

    children?: ReactElement | ReactElement[]
}

export const MainLayout:FC <Layout> = ({children}) => {
  return (
    <div className={styles.container}>
    <Head>
      <title>Mi primera APP - Kevin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar />

    <main className={styles.main}>

    
    {children}
      
    </main>
  </div>
  )
}
